version: '3.3'

services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      #- 443:443
    #volumes:
    #  - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/jenkins.conf:/etc/nginx/conf.d/jenkins.conf:ro
      - ./nginx/develop.conf:/etc/nginx/conf.d/develop.conf:ro
      - ./nginx/staging.conf:/etc/nginx/conf.d/staging.conf:ro
      - ./nginx/hotfix.conf:/etc/nginx/conf.d/hotfix.conf:ro
networks:
  backend:
    driver: bridge
