version: '3.3'

services:
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      #- 443:443
    #volumes:
    #  - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  backend:
    driver: bridge
